Gemfile.lock, lib/coach/handler.rb, lib/coach/middleware.rb, lib/coach/notifications.rb, lib/coach/version.rb, lib/spec/matchers.rb, spec/lib/coach/middleware_spec.rb, spec/lib/coach/notifications_spec.rb
Tagging logs with metadata should be something you can do along the
middleware chain. This commit implements a `log_metadata` method on all
middlewares that allows logging of arbitrary metadata, which is then
sent with all `coach.handler.finish` and `coach.request` events.
Different angle than before, @petehamilton @timrogers what're your thoughts?
=> Allows logging of metadata with coach notifications

Gemfile.lock, lib/coach/errors.rb, lib/coach/handler.rb, lib/coach/middleware_validator.rb, lib/coach/version.rb, spec/lib/coach/middleware_validator_spec.rb
Had some issues earlier debugging the trace provided by Coach if a middleware key is missing. This PR attempts to solve that by including a trace of the middleware in the output of the error message. Not spec'd yet as I wanted to get some feedback on whether this is useful.
@greysteil @isaacseymour @petehamilton, opinions?
=> Implements diagramatic errors of missing requirements

Gemfile.lock, README.md, lib/coach/handler.rb, lib/coach/middleware_item.rb, lib/coach/version.rb, lib/spec/matchers.rb, spec/lib/coach/handler_spec.rb
Heard a few people recently saying how verbose they thing the coach boilerplate code is for PS. Have looked into the issue and really we needed some way to pass config values down the chain in order to bundle our middlewares more sensibly.
I've added the behaviour that whenever you pass a lambda as a config value to a middleware `uses` call, then when the chain is built that lambda is called with the parent middleware's config hash to calculate what the config value should be for the next middleware.
It's spec'd out [here](https://github.com/gocardless/coach/blob/allow-config-inheritance/spec/lib/coach/handler_spec.rb#L99-L106) but as an example...
```ruby
module Routes::Payments
class Index < Coach::Middleware
uses Middleware::Actions::Index,
validator: PaymentsControllerFilterValidator …
```
=> Inheriting config values

Gemfile.lock, lib/coach/handler.rb, lib/coach/version.rb, lib/spec/matchers.rb, spec/lib/coach/handler_spec.rb
Very convenient for testing since it allows for dependency injection like:
```ruby
class UsersIndex < Coach::Handler
def call
db_connection = config.fetch(:db_connection)
users = db_connection.run("SELECT * from users")
[200, {}, [users.to_json]]
end
end
db = Database.connect
router.draw do
match "/users", to: Coach::Handler.new(UsersIndex, db_connection: db), via: :get
end
```
@lawrencejones @hmarr what do you think?
=> Allow Handler to take a config hash, just like Middleware

README.md, lib/coach/router.rb, spec/lib/coach/router_spec.rb
When you're inside the `routes.draw` call in a Rails app, `self` is an instance of `ActionDispatch::Routing::Mapper`. Accepting the Mapper directly lets us pass `self` in `config/routes.rb`, which means that the routes obey surrounding context (e.g. when wrapped in a `scope do ... end`) block.
This does make it slightly harder to use if you want to pass a Rails Application directly, but I'm not sure why you'd want to do that. If there is a legit reason, it'd be pretty trivial to add an alternative constructor.
@lawrencejones thoughts?
=> Make Router accept a Mapper rather than a Rails app

.rubocop.yml, lib/coach/notifications.rb, lib/coach/request_benchmark.rb, lib/coach/version.rb
Stale rubocop config is causing https://github.com/gocardless/coach/pull/10 to fail.
Will merge in once specs pass.
@greysteil FYI
=> Update Rubocop configuration

.rubocop.yml, lib/coach/notifications.rb, lib/coach/request_benchmark.rb, lib/coach/version.rb, lib/spec/matchers.rb
The rspec matchers currently depend on `third` which is only found in
Rails (http://api.rubyonrails.org/classes/Array.html#method-i-third),
not ruby.
This commit moves us to use array access at index 2 instead `x[2]`,
which is compatible with plain 'ol ruby.
=> Remove dependency on rails for RSpec matchers

spec/lib/coach/request_serializer_spec.rb
Adds a few specs for Coach::RequestSerializer instances.
These specs should gain us 100% coverage for this class.
=> Tests Coach::RequestSerializer instances

.rubocop.yml, lib/coach/handler.rb, lib/coach/version.rb, spec/lib/coach/handler_spec.rb
When running `rake routes` on a large Rails app that uses Coach, the default
inspect method makes the output very difficult to read. This commit simplifies
the inspect method to indicate that the object is an instance of
`Coach::Handler` and includes the name of the root middleware.
Example...
```
handler.inspect == '#<Coach::Handler[Routes::Novelty::JacketRequest]>'
```
=> Cleans up Coach::Handler#inspect

lib/coach/router.rb, spec/lib/coach/router_spec.rb
Previously, the router would pick up globally-defined constants
that matched names of Coach middleware, rather than triggering
`const_missing` (which is how autoloading works)
The router tests also had to be modified - previously the classes
were being defined globally rather than in the module.
=> Fix middleware lookup issue in router

lib/spec/matchers.rb
For anyone using `rspec-rails`, the `require rspec` line here was a pain - it meant they needed to add `rspec` to their gemfile for no real benefit.
=> Only require rspec/expectations when adding new matchers

.rubocop.yml, coach.gemspec, spec/lib/coach/handler_spec.rb, spec/lib/coach/notifications_spec.rb, spec/lib/coach/request_benchmark_spec.rb, spec/lib/coach/router_spec.rb
We were pointing to `0.32`, which is fairly old - this brings us up to speed.
=> Upgrade Rubocop to 0.49.1

.rubocop.yml, CHANGELOG.md, lib/coach/handler.rb, lib/coach/notifications.rb, lib/coach/version.rb, spec/lib/coach/handler_spec.rb
Currently, Coach is fairly agnostic about errors being raised within one of the middlewares. However, this leads to the unfortunate behaviour that error logging is abruptly terminated if the middleware raises an exception.
This means that any metadata from the request, that we had intentionally captured, is lost, and we only have request logs from the outer application to rely on.
This commit changes Coach::Handler to capture errors, report them on the new notification `coach.handler.error`, before re-raising the error to be handled downstream. This means that `coach.request` can also be emitted safely, allowing us to capture the request telemetry before the exception is passed on.
=> Publish AS::Notifications even on errors

LICENSE.txt, README.md, coach.gemspec
This information is notably absent. We should probably drop something like this on the bottom of all our public repositories.
=> Add licence and contributing guidelines to Coach

CHANGELOG.md, lib/coach/handler.rb, lib/coach/version.rb
This change uses ActiveSupport::Notifications.instrument to time and
publish the event for coach.handler.finish. This makes Coach consistent
with how it handles handler and middleware events. Such a change should
not break any integrations, but should probably be included in a minor bump.
The upshot of this is that integrating Coach with third-party
instrumentation tools then becomes a small bit easier. This is because
using #instrument over #publish will trigger start and end events under
the same key, if your subscriber is listening appropriately.
=> Use instrument for coach.handler.finish event

CHANGELOG.md, lib/coach/request_benchmark.rb, lib/coach/version.rb, spec/lib/coach/request_benchmark_spec.rb
Coach is very useful for capturing the duration of the middlewares within the request, but does not yield any information about the start of the first request (even though this is captured by RequestBenchmark).
This commit stores, and exposes, the initial start time of the request, which can be used by downstream subscribers for more complex calculations.
=> Capture the start time for the whole request

README.md
Coach has the ability to add metadata to ActiveSupport notifications but it's not documented.
This adds the documentation that it exists and provides an example.
=> Update README to reference logging metadata for AS notifications

.rubocop.yml, .travis.yml, README.md, coach.gemspec
Support for Ruby 2.1 [ended][1] on 1st April 2017. This drops support for it in the gem, so we now support Ruby 2.2, Ruby 2.3, Ruby 2.4 and Ruby 2.5.
We do that by:
* Setting the `required_ruby_version` in the gemspec
* Stopping running tests in Travis CI on Ruby 2.1
* Reconfiguring Rubocop to use target Ruby 2.2 onwards
This PR will be followed by one which will move our CI pipeline to CircleCI, for consistency with other GoCardless projects.
[1]: https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/
=> Deprecate support for Ruby 2.1

README.md, lib/coach/handler.rb, lib/coach/middleware.rb, lib/coach/notifications.rb, lib/coach/request_benchmark.rb, spec/lib/coach/handler_spec.rb, spec/lib/coach/notifications_spec.rb
The conventional structure of ActiveSupport::Notification keys is
"event.library". However, coach used "library.event". This commit
adds support for the preferred style and deprecates the old one
for removal in a future version.
=> Switch to reverse domain named keys for instrumentation

lib/coach/request_serializer.rb
This field name was a typo. It contains an IP, and it was always meant to be called `session_ip`
=> Rename field `session_id` to `session_ip`

README.md, docs/COMPATIBILITY.md
Following the example of Statesman, which we should do in all our OSS
repos:
https://github.com/gocardless/statesman/pull/253
=> Add compatibility policy for Ruby and Rails

lib/coach/request_serializer.rb
Reverts gocardless/coach#54
Since we're not doing the upgrade to `v2.0` yet, and this is a breaking change, it has to be reversed
=> Revert "Rename field `session_id` to `session_ip`"

lib/coach/middleware.rb, spec/lib/coach/middleware_spec.rb
Hi folks,
Hope you don't mind an unsolicited contribution, but it seems awkward for requirements not to have the same api at class level as provisions. It's only a tiny little thing, but it satisfies my OCD.
John
=> feat: Middleware.requires? to mirror Middleware.provides?

.circleci/config.yml, lib/coach/handler.rb, lib/coach/middleware.rb, lib/coach/notifications.rb, spec/lib/coach/handler_spec.rb
We deprecated this format in April 2018, so over one year later we can
safely remove it.
=> Drop deprecated notification format

README.md
We switched to Circle a while ago, so update the badge.
=> Replace TravisCI badge with CircleCI badge

.rubocop.yml, CHANGELOG.md, lib/coach/request_benchmark.rb, lib/coach/rspec.rb, spec/lib/coach/request_benchmark_spec.rb
As per our logging guidelines, `duration` should be in seconds everywhere possible, not `ms`
=> DET-69 Report `duration` in seconds

.circleci/config.yml, .rubocop.yml, CHANGELOG.md, Gemfile, README.md, coach.gemspec, lib/coach.rb, lib/coach/errors.rb, lib/coach/handler.rb, lib/coach/middleware.rb, lib/coach/middleware_item.rb, lib/coach/middleware_validator.rb, lib/coach/notifications.rb, lib/coach/request_benchmark.rb, lib/coach/request_serializer.rb, lib/coach/router.rb, lib/coach/rspec.rb, lib/coach/version.rb, spec/lib/coach/handler_spec.rb, spec/lib/coach/middleware_spec.rb, spec/lib/coach/middleware_validator_spec.rb, spec/lib/coach/notifications_spec.rb, spec/lib/coach/request_benchmark_spec.rb, spec/lib/coach/request_serializer_spec.rb, spec/lib/coach/router_spec.rb, spec/spec_helper.rb
Ruby 2.2 was end-of-lifed on 2018-03-31
https://www.ruby-lang.org/en/downloads/branches/
=> Deprecate support for Ruby 2.2

README.md, lib/coach/notifications.rb
It's currently not obvious that you need to `Coach::Notifications.subscribe!` to get `request.coach` events! ✨
=> Improve docs around notifications

CHANGELOG.md, lib/coach/request_serializer.rb, spec/lib/coach/request_serializer_spec.rb
RequestSerializer returns, among other things, the filtered http headers
of the handled request, that is: all the HTTP_* headers normally
provided by Rack with a filtering rule applied (this is useful if you
want to e.g. mask or transform the content of some headers).
Among the request headers injected by Rack into the request environment
there are two notable exceptions to the 'HTTP_' rule: both CONTENT_TYPE
and CONTENT_LENGTH are not prefixed with 'HTTP_'. (more on this on the
Rack SPEC doc [0] and the lint file [1]).
This pull request changes the headers filtering logic to take both
CONTENT_TYPE and CONTENT_LENGTH into account. RequestSerializer will now
return 'http_content_type' and 'http_content_length'.
As far as I can tell this is a backward-compatible change as we're just …
=> RequestSerializer: include Content-Type and Content-Length headers.

.rubocop.yml, README.md, bin/coach, coach.gemspec, lib/coach/cli/errors.rb, lib/coach/cli/provider_finder.rb, lib/spring/commands/coach.rb, spec/lib/coach/cli/provider_finder_spec.rb
This PR adds a new `coach` CLI that's bundled with the gem.
There's tonnes more that we could do with this, but it feels shippable now that it's been refactored pretty extensively from its original hackday form through tests.
Hopefully this is the start of us making Coach easier to use on really large codebases.
I've updated `README.md` with details on what it is and how to use it.
=> Add CLI, implement find-provider and find-chain commands

CHANGELOG.md, bin/coach, coach.gemspec, lib/coach/version.rb
commander has support for subcommands, which we need on other projects, hence good to standardise on an option parser.
=> Use commander-rb option parser instead of slop

bin/coach, lib/coach/version.rb, spec/lib/coach/cli/provider_finder_spec.rb, spec/lib/coach/handler_spec.rb
otherwise, `bundle exec coach` fails with:
```
bundler: failed to load command: coach (/Users/stevej/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/coach)
NameError: uninitialized constant Coach::VERSION
```
=> Fix missing require

CHANGELOG.md, lib/coach/handler.rb, spec/lib/coach/handler_spec.rb
Coach makes an assumption that an unhandled exception deep in the
middleware chain is going to render a HTTP 500 response. However, how
your application handles that exception will ultimately affect the
response. In Rails applications it is common to have a multitude of Rack
middleware which do some additional response handling, in particular
catching certain classes of exception and remapping them. Coach
currently just bubbles the exception back to Rails' router, which
handles the exception in it's own way.
So, if you were using `finish_handler.coach` events in logs to check
response states, you might be misled i3nto thinking that a 500 error was
issued by the application when in fact it had been remapped into
something else by a Rack middleware further up the stack.
Therefore, this …
=> Record status:0 and exception metadata when exception occurs

.circleci/config.yml, coach.gemspec, lib/coach/rspec.rb
The only change required was to be more careful about kwargs/hash
arguments in the rspec helper.
=> Get the tests to run under Ruby 3

CHANGELOG.md, README.md, lib/coach/handler.rb, lib/coach/router.rb, spec/lib/coach/handler_spec.rb, spec/lib/coach/router_spec.rb, spec/spec_helper.rb, spec/support/routes.rb
This allows us to support Zeitwerk-using Rails apps, where we can't autoload safely during app boot.
I've added builds against newer Rubies and Rails here. It seems like Coach is not compatible with Ruby 3, but I don't think that should block shipping this. We should add support for Ruby 3.0 (and probably drop support for EOL'd Rubies) in a breaking change - see #103
=> Add support for route names rather than classes in Handler and Router

lib/coach/handler.rb
Previously we relied on `ActiveSupport::Dependencies.constantize` to load the name of the module this method is removed in rails 7 due to the classic autoloader being removed -
see https://github.com/rails/rails/pull/43058 for details.
Instead we can simply call `name.constantize`
=> Fix middleware constant resolution in Rails 7

lib/coach/handler.rb, spec/lib/coach/handler_spec.rb, spec/lib/coach/router_spec.rb
The constantize method in `ActiveSupport::Dependencies` has been removed and the method in the String class just forwards to the inflector implementation. This change calls the inflector implementation directly to reduce complexity
=> Use inflector constantize method in handler
